hcr_plot_example=function(U.min,eg.limit,upper.tar,smax0,smsy,target.ER){
  plot(c(0,1)~c(0,smax0*1.5),ylab='Target harvest',xlab='Run size',type='n')
  lines(rep(U.min,2)~c(0,eg.limit[3]),lwd=2)
  lines(c(U.min,target.ER[1])~c(eg.limit[1],upper.tar[1]),lwd=2,col='goldenrod')
  lines(rep(target.ER[1],2)~c(upper.tar[1],smax0*1.5),lwd=2,col='goldenrod')
  lines(c(U.min,target.ER[2])~c(eg.limit[2],upper.tar[2]),lwd=2,col='darkred')
  lines(rep(target.ER[2],2)~c(upper.tar[2],smax0*1.5),lwd=2,col='darkred')
  lines(c(U.min,target.ER[3])~c(eg.limit[3],upper.tar[3]),lwd=2,col='navy')
  lines(rep(target.ER[3],2)~c(upper.tar[3],smax0*1.5),lwd=2,col='navy')
  text(x=par('usr')[2]*0.9,y=target.ER[1]*1.1,paste(round(umsy[1],2)),col='goldenrod',cex=0.7)
  text(x=par('usr')[2]*0.9,y=target.ER[2]*1.1,paste(round(umsy[2],2)),col='darkred',cex=0.7)
  text(x=par('usr')[2]*0.9,y=target.ER[3]*1.1,paste('Umsy=',round(umsy[3],2)),col='navy',cex=0.7)
  text(x=eg.limit[1],y=0.005,paste('Smsy=',round(smsy[1],0)),col='goldenrod',cex=0.7)
  text(x=eg.limit[2],y=0.005,paste(round(smsy[2],0)),col='darkred',cex=0.7)
  text(x=eg.limit[3],y=0.005,paste(round(smsy[3],0)),col='navy',cex=0.7)
  text(x=par('usr')[2]*0.1,y=par('usr')[4]*0.85,'time point 3',col='goldenrod',cex=0.8)
  text(x=par('usr')[2]*0.1,y=par('usr')[4]*0.9, 'time point 2',col='darkred',cex=0.8)
  text(x=par('usr')[2]*0.1,y=par('usr')[4]*0.95, 'time point 1',col='navy',cex=0.8)
}

hcr_plot_est=function(sim.df,tp,eg.limit,upper.tar,U.min,target.ER,title){
  if(is.null(title)==T){title=''}
  plot(c(0,1)~c(0,2*max(upper.tar[tp])),ylab='Target harvest',xlab='Run size',type='n',main=title)
  lines(sim.df$harvest.rate~sim.df$run.size,col=adjustcolor('darkgray',alpha.f=0.5))
  points(sim.df$harvest.rate~sim.df$run.size)
  text(x=sim.df$run.size,y=sim.df$harvest.rate+.025,sim.df$by,cex=0.5)
  lines(rep(U.min,2)~c(0,max(eg.limit[tp])),lwd=2)
  lines(c(U.min,target.ER[tp[1]])~c(eg.limit[tp[1]],upper.tar[tp[1]]),lwd=2,col='navy')
  lines(c(U.min,target.ER[tp[1]])~c(eg.limit[tp[1]],upper.tar[tp[1]]),lwd=2,col='navy')
  lines(rep(target.ER[tp[1]],2)~c(upper.tar[tp[1]],2*max(upper.tar)),lwd=2,col='navy')
  lines(c(U.min,target.ER[tp[2]])~c(eg.limit[tp[2]],upper.tar[tp[2]]),lwd=2,col='darkred')
  lines(c(U.min,target.ER[tp[2]])~c(eg.limit[tp[2]],upper.tar[tp[2]]),lwd=2,col='darkred')
  lines(rep(target.ER[tp[2]],2)~c(upper.tar[tp[2]],2*max(upper.tar)),lwd=2,col='darkred')
  lines(c(U.min,target.ER[tp[3]])~c(eg.limit[tp[3]],upper.tar[tp[3]]),lwd=2,col='goldenrod')
  lines(c(U.min,target.ER[tp[3]])~c(eg.limit[tp[3]],upper.tar[tp[3]]),lwd=2,col='goldenrod')
  lines(rep(target.ER[tp[3]],2)~c(upper.tar[tp[3]],2*max(upper.tar)),lwd=2,col='goldenrod')
  text(x=par('usr')[2]*0.1,y=par('usr')[4]*0.85, paste('year', tp[3]),col='goldenrod',cex=0.8)
  text(x=par('usr')[2]*0.1,y=par('usr')[4]*0.9, paste('year', tp[2]),col='darkred',cex=0.8)
  text(x=par('usr')[2]*0.1,y=par('usr')[4]*0.95, paste('year', tp[1]),col='navy',cex=0.8)
  text(x=par('usr')[2]*0.9,y=target.ER[tp[3]]*1.05,paste(round(sim.df$umsy.est[tp[3]],2)),col='goldenrod',cex=0.8)
  text(x=par('usr')[2]*0.9,y=target.ER[tp[2]]*1.05,paste(round(sim.df$umsy.est[tp[2]],2)),col='darkred',cex=0.8)
  text(x=par('usr')[2]*0.9,y=target.ER[tp[1]]*1.05,paste(round(sim.df$umsy.est[tp[1]],2)),col='navy',cex=0.8)
  text(x=eg.limit[tp[3]],y=0,paste(round(sim.df$smsy.est[tp[3]],0)),col='goldenrod',cex=0.8)
  text(x=eg.limit[tp[2]],y=-0.01,paste(round(sim.df$smsy.est[tp[2]],0)),col='darkred',cex=0.8)
  text(x=eg.limit[tp[1]],y=0.01,paste(round(sim.df$smsy.est[tp[1]],0)),col='navy',cex=0.8)
  points(sim.df$umsy.true[tp[3]]~sim.df$smsy.true[tp[3]],pch=21,cex=2,bg='goldenrod')
  points(sim.df$umsy.true[tp[2]]~sim.df$smsy.true[tp[2]],pch=21,cex=2,bg='darkred')
  points(sim.df$umsy.true[tp[1]]~sim.df$smsy.true[tp[1]],pch=21,cex=2,bg='navy')
  points(sim.df$harvest.rate~sim.df$run.size)
}